import type { DiffReport, Report } from '@shared/report';

function pad(n: number): string {
  return n.toLocaleString('en-US');
}

function pct(n: number, total: number): string {
  if (total === 0)
    return '0%';
  return `${((n / total) * 100).toFixed(1)}%`;
}

export function exportMarkdown(report: Report, diff?: DiffReport | null): string {
  const lines: string[] = [];
  lines.push('# TallyCode Report');
  lines.push('');
  lines.push(`- **Root**: \`${report.rootPath}\``);
  if (report.scope)
    lines.push(`- **Scope**: \`${report.scope}\``);
  lines.push(`- **Scanned**: ${report.scannedAt}`);
  lines.push(`- **Duration**: ${report.durationMs} ms`);
  lines.push('');

  /* Summary */
  lines.push('## Summary');
  lines.push('');
  lines.push('| Metric | Value |');
  lines.push('|---|---|');
  lines.push(`| Total files | ${pad(report.summary.totalFiles)} |`);
  lines.push(`| Source files | ${pad(report.summary.sourceFiles)} |`);
  lines.push(`| Test files | ${pad(report.summary.testFiles)} (${pct(report.summary.testFiles, report.summary.totalFiles)}) |`);
  lines.push(`| Languages | ${pad(report.summary.languageCount)} |`);
  lines.push(`| **Total lines** | **${pad(report.summary.total.total)}** |`);
  lines.push(`| Code lines | ${pad(report.summary.total.code)} |`);
  lines.push(`| Comment lines | ${pad(report.summary.total.comment)} |`);
  lines.push(`| Blank lines | ${pad(report.summary.total.blank)} |`);
  lines.push(`| Source code | ${pad(report.summary.source.code)} |`);
  lines.push(`| Test code | ${pad(report.summary.test.code)} |`);
  lines.push('');

  /* Languages */
  lines.push('## By Language');
  lines.push('');
  lines.push('| Language | Files | Source code | Test code | Comment | Blank | Total |');
  lines.push('|---|---:|---:|---:|---:|---:|---:|');
  for (const lang of report.languages) {
    lines.push(`${[
      `\`${lang.language}\``,
      `${lang.files} (${lang.testFiles} test)`,
      pad(lang.source.code),
      pad(lang.test.code),
      pad(lang.total.comment),
      pad(lang.total.blank),
      pad(lang.total.total),
    ].join(' | ')} |`);
  }
  lines.push('');

  /* Top files */
  lines.push('## Top 20 Files by Code Lines');
  lines.push('');
  lines.push('| File | Lang | Test | Code | Comment | Blank | Total |');
  lines.push('|---|---|:--:|---:|---:|---:|---:|');
  const top = [...report.files].sort((a, b) => b.count.code - a.count.code).slice(0, 20);
  for (const f of top) {
    lines.push(`${[
      `\`${f.path}\``,
      `\`${f.language}\``,
      f.isTest ? '✓' : '',
      pad(f.count.code),
      pad(f.count.comment),
      pad(f.count.blank),
      pad(f.count.total),
    ].join(' | ')} |`);
  }
  lines.push('');

  /* Skipped */
  if (report.skipped.length > 0) {
    lines.push('## Skipped');
    lines.push('');
    lines.push('| Path | Reason | Size |');
    lines.push('|---|---|---:|');
    for (const s of report.skipped.slice(0, 50)) {
      lines.push(`| \`${s.path}\` | ${s.reason} | ${s.size ? pad(s.size) : '—'} |`);
    }
    if (report.skipped.length > 50) {
      lines.push(`| … | … and ${report.skipped.length - 50} more | — |`);
    }
    lines.push('');
  }

  /* Diff */
  if (diff) {
    lines.push('## Diff vs Baseline');
    lines.push('');
    const d = diff.summary.delta;
    const sign = (n: number): string => (n > 0 ? `+${pad(n)}` : pad(n));
    lines.push(`- Baseline: ${diff.baselineAt}`);
    lines.push(`- Current : ${diff.currentAt}`);
    lines.push('');
    lines.push('| Metric | Before | After | Δ |');
    lines.push('|---|---:|---:|---:|');
    lines.push(`| Total files | ${pad(diff.summary.filesBefore)} | ${pad(diff.summary.filesAfter)} | ${sign(diff.summary.filesAfter - diff.summary.filesBefore)} |`);
    lines.push(`| Files added | — | ${pad(diff.summary.filesAdded)} | — |`);
    lines.push(`| Files removed | — | ${pad(diff.summary.filesRemoved)} | — |`);
    lines.push(`| Files changed | — | ${pad(diff.summary.filesChanged)} | — |`);
    lines.push(`| Code lines | ${pad(diff.summary.before.code)} | ${pad(diff.summary.after.code)} | ${sign(d.code)} |`);
    lines.push(`| Comment lines | ${pad(diff.summary.before.comment)} | ${pad(diff.summary.after.comment)} | ${sign(d.comment)} |`);
    lines.push(`| Blank lines | ${pad(diff.summary.before.blank)} | ${pad(diff.summary.after.blank)} | ${sign(d.blank)} |`);
    lines.push(`| Total lines | ${pad(diff.summary.before.total)} | ${pad(diff.summary.after.total)} | ${sign(d.total)} |`);
    lines.push('');
  }

  lines.push('---');
  lines.push('');
  lines.push('*Generated by TallyCode.*');
  return lines.join('\n');
}
